/*
 * protocolos.h
 *
 *  Created on: 25 may. 2018
 *      Author: utnso
 */

#include <commons/collections/dictionary.h>
#include "manejoDeSockets/manejoDeSockets.h"

#ifndef PROTOCOLOS_PROTOCOLOS_H_
#define PROTOCOLOS_PROTOCOLOS_H_

typedef enum PROTOCOLO_COORDINADOR_A_CLIENTES{
	HANDSHAKE_CONECTAR_COORDINADOR_A_CLIENTES,
	TODO_OK,
	TODO_MAL
}PROTOCOLO_COORDINADOR_A_CLIENTES;

typedef enum PROTOCOLO_ESI_A_COORDINADOR{
	HANDSHAKE_CONECTAR_ESI_A_COORDINADOR,

}PROTOCOLO_ESI_A_COORDINADOR;


typedef enum PROTOCOLO_INSTRUCCIONES{
	INSTRUCCION_GET,
	INSTRUCCION_SET,
	INSTRUCCION_STORE
}PROTOCOLO_INSTRUCCIONES;

typedef enum PROTOCOLO_ESI_A_PLANIFICADOR{
	HANDSHAKE_CONECTAR_ESI_A_PLANIFICADOR
}PROTOCOLO_ESI_A_PLANIFICADOR;

typedef enum PROTOCOLO_PLANIFICADOR_A_ESI{
	HANDSHAKE_CONECTAR_PLANIFICADOR_A_ESI
}PROTOCOLO_PLANIFICADOR_A_ESI;

typedef enum PROTOCOLO_INSTANCIA_A_COORDINADOR{
	HANDSHAKE_CONECTAR_INSTANCIA_A_COORDINADOR
}PROTOCOLO_INSTANCIA_A_COORDINADOR;

/*
typedef enum PROTOCOLO_PLANIFICADOR_A_COORDINADOR{

}PROTOCOLO_PLANIFICADOR_A_COORDINADOR;

typedef enum PROTOCOLO_COORDINADOR_A_PLANIFICADOR{

}PROTOCOLO_COORDINADOR_A_PLANIFICADOR;

typedef enum PROTOCOLO_COORDINADOR_A_INSTANCIA{

}PROTOCOLO_COORDINADOR_A_INSTANCIA;



*/
#endif /* PROTOCOLOS_PROTOCOLOS_H_ */
