all:
	-cd library && make all
	-cd Coordinador &&  make all
	-cd Esi && make all
	-cd Instancia && make all
	-cd Planificador && make all
clean:
	-cd library && make clean
	-cd Coordinador &&  make clean
	-cd Esi && make clean
	-cd Instancia && make clean
	-cd Planificador && make clean